const product = [
  {
    id: 1,
    image: "../images/product-img1.jpg",
    discount: "20%",
    productName: "Summer Wear",
    categoryName: "T-shirt",
    price: "Rs.2000",
    discountedPrice: "Rs.2500",
  },
  {
    id: 2,
    image: "../images/product-img2.jpg",
    discount: "20%",
    productName: "Autumn Wear",
    categoryName: "Shirt",
    price: "Rs.3000",
    discountedPrice: "Rs.3500",
  },
  {
    id: 3,
    image: "../images/product-img3.jpeg",
    discount: "20%",
    productName: "Winter Wear",
    categoryName: "Wollen Jacket",
    price: "Rs.1500",
    discountedPrice: "Rs.2000",
  },
  {
    id: 4,
    image: "../images/product-img-4.jpg",
    discount: "20%",
    productName: "Formal Wear",
    categoryName: "Suit",
    price: "Rs.1800",
    discountedPrice: "Rs.2200",
  },
  {
    id: 5,
    image: "../images/product-img1.jpg",
    discount: "20%",
    productName: "Summer Wear",
    categoryName: "T-shirt",
    price: "Rs.2000",
    discountedPrice: "Rs.2500",
  },
  {
    id: 6,
    image: "../images/product-img2.jpg",
    discount: "20%",
    productName: "Autumn Wear",
    categoryName: "Shirt",
    price: "Rs.3000",
    discountedPrice: "Rs.3500",
  },
  {
    id: 7,
    image: "../images/product-img3.jpeg",
    discount: "20%",
    productName: "Winter Wear",
    categoryName: "Wollen Jacket",
    price: "Rs.1500",
    discountedPrice: "Rs.2000",
  },
  {
    id: 8,
    image: "../images/product-img-4.jpg",
    discount: "20%",
    productName: "Formal Wear",
    categoryName: "Suit",
    price: "Rs.1800",
    discountedPrice: "Rs.2200",
  },
];

export default product;
